spring:
  application:
    name: whu-treehole-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${TREEHOLE_NACOS_SERVER_ADDR:localhost:8848}
  data:
    redis:
      host: ${TREEHOLE_REDIS_HOST:localhost}
      port: ${TREEHOLE_REDIS_PORT:6379}
      password: ${TREEHOLE_REDIS_PASSWORD:}
      timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${TREEHOLE_GATEWAY_PORT:8080}
