spring:
  application:
    name: whu-treehole-message-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TREEHOLE_DB_HOST:localhost}:${TREEHOLE_DB_PORT:3306}/${TREEHOLE_DB_NAME:se_project}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${TREEHOLE_DB_USERNAME:root}
    password: ${TREEHOLE_DB_PASSWORD:}

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${TREEHOLE_MESSAGE_PORT:8081}
